version: '3.8'

services:
  app:
    image: ghcr.io/s4ke/docker-swarm-multitenant-proxy:0.2.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - OWNER_LABEL_VALUE=your-owner-label-value
      - ALLOWED_REGULAR_VOLUMES_DRIVERS=local
      - ALLOWED_VOLUME_TYPES=bind,volume,tmpfs,npipe,cluster
      - ALLOW_PORT_EXPOSE=true
      - TLS_KEY_FILE=/run/secrets/tls_key
      - TLS_CERT_FILE=/run/secrets/tls_cert
      - TLS_CA_FILE=/run/secrets/tls_ca
      - TLS_DISABLE=false
    user: root
    secrets:
      - tls_key
      - tls_cert
      - tls_ca
    ports:
      - "8081:8080"
    deploy:
      replicas: 1

secrets:
  tls_key:
    file: ./server-key.pem
  tls_cert:
    file: ./server-cert.pem
  tls_ca:
    file: ./ca-cert.pem

networks:
  app-network:
    driver: overlay
